### ISSUE TITLE
Hi can i have ur contact i have the similaire project but i couldn't know where to start 

### ISSUE THREAD

**Issue by Sarahwidad** [ghimireadarsh/Smart-Glove#20]

**Comment by ghimireadarsh** [comment]
please email me at adarshghimire5@gmail.com

**Comment by Sarahwidad** [comment]
Hi i hope  you are doing well so
As i am an electrical and électronique engeneering L3 and as a bachelor's
project
I am doing the project of" the smart glove"
 So had some few question to you i am so hoping that you answer me :
First: what are the programs that you used in the programation of the
software of the project (doe example :arduino ide , anaconda
,python,matlab......)
Second  question : how can i use my arduno ide output as an input to my
machine learning programme .
Third question: why did you use the algorithm of random forest and how did
you made that data set (it's nexassary in my university to show them how we
got the dataset ) and is it possible to tell me how to use the data set
when it's a picture because i've just been working with csv data set for so
long so i don't know maybe you can share a youtub link that can help me
dith that kind of data set .
4th question: how did you differentiate between the two letters u and v
knowing that in ASL they have almpst same sign comparing to the flex sensor
.
I really appreciate your time and am looking forward to your answer .
Thank you so much from now best regard and best wishes .

**Comment by ghimireadarsh** [comment]
Hi, 
1. First: what are the programs that you used in the programation of the software of the project (doe example :arduino ide , anaconda, python, matlab......) --> __Arduino and Python__

2. Second  question : how can i use my arduno ide output as an input to my machine learning programme . --> __You can use serial interface to capture the data coming from your arduino__

3. Third question: why did you use the algorithm of random forest and how did you made that data set (it's nexassary in my university to show them how we got the dataset ) and is it possible to tell me how to use the data set when it's a picture because i've just been working with csv data set for so long so i don't know maybe you can share a youtub link that can help me dith that kind of data set. --> __We tried other algorithms as well but random forest gave us more accurate result with negligible difference in time to process. We collected our own dataset with our sensor setups. Regarding picture, do you mean you want the camera setup to capture and process the sign language?__ 

4. 4th question: how did you differentiate between the two letters u and v knowing that in ASL they have almpst same sign comparing to the flex sensor. --> __Interms of flex sensor only, yes you are right they will have similar values however, we not only have flex sensor but gyro and accelerometer, which gives the more information about the orientation and swing. Infact, I must say that for those ambiguous signs we had confusing responses.__

Good luck!

**Comment by Sarahwidad** [comment]
Thank you for your answer.  It's so helpful for me
Thank you very much for your time i really appreciate it
